# site name
prefixName: 樱花庄的
siteName: 風
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /images/custom/avatar.jpg
url: https://kaze0617.gitee.io/
description: No game no life !
cdn: https://cdn.jsdelivr.net/gh/kaze0617/cdn@2.3
pjax: 1
# 1开启
mathjax: 0

notice: hexo-Sakura主题已经开源，目前正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/kaze0617/cdn@2.3/images/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    随笔: {path: /categories/随笔/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  学习: {path: javascript:;,fa: fa-book faa-vertical, submenus: {
    JAVA: {path: /categories/Java/,fa: fa-file-code-o}
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: javascript:;, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  黑苹果: { path: javascript:;, fa: fa-apple faa-bounce , submenus: {
    支持 : {path: /categories/支持, fa: fa-cogs  faa-pulse},
    镜像 : {path: /categories/镜像, fa: fa-arrow-circle-o-down faa-bounce},
    工具 : {path: /categories/工具, fa: fa-wrench faa-shake},
    完善 : {path: /categories/完善, fa: fa-check-circle faa-shake},
  } }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - /images/cover/0.webp
  - /images/cover/1.webp
  - /images/cover/2.webp
  - /images/cover/3.webp
  - /images/cover/4.webp
  - /images/cover/5.webp
  - /images/cover/6.webp
  - /images/cover/7.webp
  - /images/cover/8.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-grid

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /images/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/84859683, title: Bilibili, desc: 博主的b站视频, img: /images/startdash/bilibili.jpg}
  - {url: /categories/技术/, title: KAZE的万事屋, desc: 技术服务, img: /images/startdash/wanshiwu.jpg}

# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PC端配置
social:
  github: {url: http://github.com/kaze0617, img: /images/social/github.png}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1515097306&site=qq&menu=yes, img: /images/social/qq.png}
  gitee: {url: https://gitee.com/kaze0617, img: /images/social/gitee.png}
#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/kaze0617, fa: fa-github, color: 333}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1515097306&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  alipay: /images/donate/AliPayQR.png
  wechatSQ: /images/donate/WechatQR.png
  wechat: /images/donate/WechatQR.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/kaze0617/cdn@2.3
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Apple.mp4

aplayer: 
  switch: true
  id: 7527603935
  server: tencent
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.2
  mutex: true

# Valine
valine: true
v_appId: Aiy3G092H2AXI5Ad0mFMBugP-MdYXbMMI
v_appKey: CoDqXAC8Qk2n7Nw1ikqhNmvk
v_verify: true

font:
  enable: true
  # Uri of fonts host. E.g. //fonts.googleapis.com (Default)
  host: //fonts.proxy.ustclug.org